# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3d893ec2ca23e8871044fb7f03493f63949ac82daba4480b8b7b27cb09618a9857ce8ee3e1f0366b028b70eecb262c418e93d31af415bff688394bdf5c41ae1

test:
  secret_key_base: 06e714cfdb944c8d9e70961ea706de69b3f05aaf04d6c38ac11d064d0139016bbf3531bd8aa9403dd92daf7ce2d97eb59f324c5cdbda38186f4a3f5f4b116e62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
