# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c2f0177ea3e1c85aa80216d7015f1de1d56f7efdc605ff5541337638d85bc68e2aada5147162537f808d988ed76dcce222971b0472aa978ee376b32bf8b61c7

test:
  secret_key_base: 4250fed6aeb0ab2fe16e0f762da3800e15a865770fe3791afc919d8a708761280f6c925d08a21e42b605b5edb867c98b050361b536630ed1b10f55670f60d669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
